"""Initial schema

Revision ID: 9c1e97a280c8
Revises: 
Create Date: 2026-09-10 00:30:12.358235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c1e97a280c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('daily_allowance_sar', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('home_currency', sa.String(length=3), nullable=False),
    sa.Column('travel_currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_trip_id'), ['trip_id'], unique=False)

    op.create_table('exchange_rate_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('sar_to_pkr', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exchange_rate_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exchange_rate_snapshots_is_latest'), ['is_latest'], unique=False)
        batch_op.create_index(batch_op.f('ix_exchange_rate_snapshots_trip_id'), ['trip_id'], unique=False)

    op.create_table('exchange_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('pkr_given', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sar_received', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('acquisition_rate', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exchange_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exchange_transactions_trip_id'), ['trip_id'], unique=False)

    op.create_table('shopping_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('expected_sar', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('is_purchased', sa.Boolean(), nullable=False),
    sa.Column('actual_sar', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shopping_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shopping_items_trip_id'), ['trip_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('amount_sar', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('pkr_equivalent', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('acquisition_rate_used', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('subcategory_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('shopping_item_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("location IN ('Makkah', 'Madinah', 'Jeddah', 'Other')", name='ck_transaction_location'),
    sa.CheckConstraint("type IN ('EXPENSE', 'REFUND')", name='ck_transaction_type'),
    sa.CheckConstraint('amount_sar > 0', name='ck_transaction_amount_positive'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['shopping_item_id'], ['shopping_items.id'], ),
    sa.ForeignKeyConstraint(['subcategory_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_trip_id'), ['trip_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_trip_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('shopping_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shopping_items_trip_id'))

    op.drop_table('shopping_items')
    with op.batch_alter_table('exchange_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exchange_transactions_trip_id'))

    op.drop_table('exchange_transactions')
    with op.batch_alter_table('exchange_rate_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exchange_rate_snapshots_trip_id'))
        batch_op.drop_index(batch_op.f('ix_exchange_rate_snapshots_is_latest'))

    op.drop_table('exchange_rate_snapshots')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_trip_id'))
        batch_op.drop_index(batch_op.f('ix_categories_parent_id'))

    op.drop_table('categories')
    op.drop_table('trips')
    # ### end Alembic commands ###
